### ISSUE TITLE
提示目录不可写

### ISSUE THREAD

**Issue by Bronya-Rayi** [DasSecurity-Labs/AoiAWD#1]
PHP Fatal error:  Uncaught Error: Document root requires a readable directory in xxx
windows和Linux环境经试验都不可以
linux目录权限为777，windows目录权限为可读可写
![image](https://user-images.githubusercontent.com/47048823/94148957-e13cae80-fea9-11ea-9de2-b4b232e7ff27.png)
![image](https://user-images.githubusercontent.com/47048823/94149031-f44f7e80-fea9-11ea-990e-58b396e3cae9.png)

**Comment by aodzip** [comment]
出现此报错的原因是没有编译Frontend组件并放到AoiAWD/src/public目录下（可能需要自己创建）

**Comment by Bronya-Rayi** [comment]
感谢大佬，目录不可写的问题解决了，现在就是编译组件后再进行打包phar会非常慢，估计得打包两三个小时
![image](https://user-images.githubusercontent.com/47048823/94222470-01a75000-ff20-11ea-87c9-cb28d64b2b49.png)

**Comment by aodzip** [comment]
不对啊，Frontend编译后只有几个文件，你这node modules都出来了😂

**Comment by Bronya-Rayi** [comment]
是我菜了师傅，已经搭好了，完美运行，tql
