### ISSUE TITLE
编译RoundWorm时报错

### ISSUE THREAD

**Issue by summerN** [DasSecurity-Labs/AoiAWD#2]
src/io.c:3:34: fatal error: inotifytools/inotify.h: 没有那个文件或目录
compilation terminated.
Makefile:16: recipe for target 'src/io.o' failed
make: *** [src/io.o] Error 1

**Comment by summerN** [comment]
gcc -Wall -Wextra -I ./src -std=c99 -march=x86-64 -c src/io.c -o src/io.o
src/io.c:3:34: fatal error: inotifytools/inotify.h: 没有那个文件或目录
compilation terminated.
Makefile:16: recipe for target 'src/io.o' failed
make: *** [src/io.o] Error 1

**Comment by aodzip** [comment]
apt install libinotifytools0-dev

**Comment by summerN** [comment]
解决了，谢谢师傅
