### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by ahuiccc666** [DasSecurity-Labs/AoiAWD#20]
请问，flagbuster没有效果该咋办

**Comment by aodzip** [comment]
应该是你没有命中flag的正则，建议参考插件源码

**Comment by ahuiccc666** [comment]
> 应该是你没有命中标志的正则，建议参考插件源码
是诶，谢谢师傅

**Comment by yuqie-sys** [comment]
请问一下，TapeWorm插件运行显示Can not connect to log center，权限我也赋予了，为啥还是执行不了呀
