### ISSUE TITLE
前面都成功，在部署Guardian时报错

### ISSUE THREAD

**Issue by Hofiy** [DasSecurity-Labs/AoiAWD#5]
![1](https://user-images.githubusercontent.com/56147994/94341847-5c839900-003f-11eb-95f1-5aad18fdf53a.jpg)
师傅求助=w=

**Comment by aodzip** [comment]
内核头文件不支持MEMFD

**Comment by Hofiy** [comment]
那请问怎么样才能使其支持呢，是我ubuntu版本太低了嘛师傅？

**Comment by aodzip** [comment]
对，用新版的
