### ISSUE TITLE
创建socket服务显示没有权限

### ISSUE THREAD

**Issue by orio1e** [DasSecurity-Labs/AoiAWD#8]
我的PHP扩展已经安装了但是开的时候显示如下的报错  大佬求教
![图片](https://user-images.githubusercontent.com/45875494/94365172-45a57b00-0101-11eb-95a6-b1411102dbf5.png)
最主要是以下的这个报错：
PHP Fatal error:  Uncaught Amp\Socket\SocketException: Could not create server tcp://0.0.0.0:1337: [Error: #0] Permission denied

**Comment by aodzip** [comment]
我看你好像是用WSL运行的，在虚拟机里运行一下试试？

**Comment by orio1e** [comment]
感谢大佬 用虚拟机就可以了
